### ISSUE TITLE
encoder support  VIDEO_DATA_MEMORY_TYPE_SURFACE_ID ?

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#201]
你好，打扰了！编码时候只能传VIDEO_DATA_MEMORY_TYPE_RAW_POINTER？ 不支持直接在显卡解码后生产的surface转给编码？
VideoFrameRawData vfd;
        memset(&vfd,0,sizeof(vfd));
        vfd.memoryType = VIDEO_DATA_MEMORY_TYPE_SURFACE_ID;
        vfd.internalID = vrb->surface;
        vfd.handle = (intptr_t)vrb->display;
        vfd.flags = VIDEO_FRAME_FLAGS_KEY;
        vfd.width = 1280;
        vfd.height = 720;
        vfd.fourcc = VA_FOURCC_NV12;
        encoder_->encode(&vfd);

**Comment by xuguangxin** [comment]
Yes. as workaround,  you can get VIDEO_DATA_MEMORY_TYPE_RAW_POINTER from decoder and send it to encoder. We have a demo about this in EncodeInputDecoder.cpp. It's not efficient. Since it force cpu/gpu sync and copy  bits from decode surface to encode surface. But it's dependent your usage.  May it's enough for you. 
We will add vpp(video post process) interface in near future, it enable you share surface between vpp and encoder with out copy any thing. But share surface between decoder and encoder is more difficult,it in our long term plan, but not have time table yet.

**Comment by xuguangxin** [comment]
Hi wait89:
Now, you can use SharedPtr<VideoFrame> IVideoDecoder::getOutput() && IVideoEncoder::encode(const SharedPtr<VideoFrame>& frame) to achieve this. 
details you can refer to https://github.com/01org/libyami/blob/master/examples/simpleplayer.cpp && https://github.com/01org/libyami/blob/master/tests/vppoutputencode.cpp
thanks.

**Comment by xuguangxin** [comment]
Hi waiter89:
If you think this issue is not fixed. Please repoen it.
thanks
