### ISSUE TITLE
What version of libyami supports VP8/VP9 and HEVC encode and decode

### ISSUE THREAD

**Issue by laxigithub** [01org/libyami#550]
Could you help what version of libyami support VP8/VP9 and HEVC encode and decode. 

from yamiinfo , the API I am getting is: 0.2.0. 
Please help if this is the right way to know the libyami  version info.

**Comment by chivakker** [comment]
On Wed, Aug 31, 2016 at 1:49 PM, Laxman notifications@github.com wrote:

> Could you help what version of libyami support VP8/VP9 and HEVC encode and
> decode.
> 
> from yamiinfo , the API I am getting is: 0.2.0.
> Please help if this is the right way to know the libyami version info.

yamiinfo will also list the compiled components

i.e. $yamiinfo

libyamiutils 0.1.0 - https://github.com/01org/libyami-utils

API: 0.2.0

decoders:
        image/jpeg
        video/avc
        video/h264
        video/mpeg2
        video/x-vnd.on2.vp8

encoders:
        video/avc
        video/h264
        video/x-vnd.on2.vp9

post processors:
        vpp/scaler

Combine it with the output from vainfo.

## 

Daniel.

**Comment by laxigithub** [comment]
the playback with libyami appears to be fast forward playback like 2X speed. is it dependent on any rendering framework ? Please suggest how this could be fixed ?

**Comment by chivakker** [comment]
On Thu, Sep 1, 2016 at 11:35 AM, Laxman notifications@github.com wrote:

> the playback with libyami appears to be fast forward playback like 2X
> speed. is it dependent on any rendering framework ? Please suggest how this
> could be fixed ?

yamidecode (an example test for video decoding) is running without a clock
or any synchronization mechanism, depending on the mode you're choosing it
can be throttled to different speeds (but not because yamidecode can do
such thing).  We would need to know more how your multimedia stack looks
like to provide more insight on your options.

## 

Daniel.
