### ISSUE TITLE
Need fix all gtest failure things.

### ISSUE THREAD

**Issue by xuguangxin** [01org/libyami#741]
Currently, we have 7 issues on SKL, we need to fix them.
CompatibleX11  
CreateX11  
Format_Change/0  
Format_Change/1  
ReadAsUnits  
ReadAsWhole 
guessResolutionOverflow

**Comment by uartie** [comment]
For the X11 based tests, we should allow those to be disabled/enabled at runtime since not all test environments will have an X server running (e.g. servers).  We could do that by prefixing the test names with DISABLED_ (i.e. gtest framework skips [DISABLED_](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#temporarily-disabling-tests) prefixed tests by default, but can be enabled with command line)... or we can check an environment variable set by the user (e.g. YAMI_ENABLE_X11_TESTS=[0|1]).

The ReadAsUnits, ReadAsWhole and guessResolutionOverflow test cases are already fixed by #730... it just needs final review and merged.

**Comment by xuguangxin** [comment]
Thanks for suggestion, we will look it.

after #730 merge.
We have 4 issue left

CompatibleX11  
CreateX11  
Format_Change/0  
Format_Change/1

**Comment by uartie** [comment]
On SKL and BSW, we also have these failures in decode unittest:

Flush/3
Format_Change/3

...which aren't supported on these platforms and should be skipped at runtime.  This means we need a runtime support check feature.  Currently, those tests segfault on these platforms.

**Comment by xuguangxin** [comment]
@uartie , it still needs more work to add run-time check in yami. Let use add some check in gtest first. I will send a pull request this week.

**Comment by xuguangxin** [comment]
with #754, all issues fixed
